version: '3'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -rf tmp/* && mkdir -p tmp/sockets && chown -R 1000:1000 tmp && chmod -R 777 tmp && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    user: "1000:1000"

volumes:
  postgres_data: