default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: note_taker_development

test:
  <<: *default
  database: note_taker_test

production:
  <<: *default
  database: note_taker_production